# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 09:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa')),
                ('organizer', models.CharField(max_length=100, verbose_name='Organizator')),
                ('city', models.CharField(max_length=100, verbose_name='Miasto')),
                ('date', models.DateTimeField(verbose_name='Data')),
                ('address', models.CharField(max_length=100, verbose_name='Miejsce')),
                ('image', models.ImageField(upload_to='images', verbose_name='Zdjęcie')),
                ('url', models.URLField(blank=True, default='', max_length=100, verbose_name='Link do zapisów')),
                ('last_edit_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
