# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='last_edit_author',
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(upload_to='media', verbose_name='Zdjęcie'),
        ),
    ]
